### ISSUE TITLE
 ImportError: No module named 'caffeine'

### ISSUE THREAD

**Issue by ManuelSchneid3r** [hobarrera/caffeine-ng#22]
```
$ caffeine 
Traceback (most recent call last):
  File "/usr/bin/caffeine", line 19, in <module>
    from caffeine.main import main
ImportError: No module named 'caffeine'
```

Archlinux
caffeine-ng 3.1-1

**Comment by rumpelsepp** [comment]
You have already rebuild it, due to the python 3.5 upgrade?

**Comment by ManuelSchneid3r** [comment]
I receive it by AUR. But shasum is broken atm.

**Comment by hobarrera** [comment]
This is probably due to the python3.5 upgrade. You need to rebuild all python packages for this to work. I also briefly broke the PKGBUILD too today (sorry about that), but it should be working fine.

For future reference, you can list any package you need to rebuild via:

    pacman -Qo /usr/lib/python3.4

Note that binary packages will probably auto-update. You'll only need to rebuild AUR packages.

**Comment by ManuelSchneid3r** [comment]
Thank you.
